### ISSUE TITLE
Does CustomSimulatorsExample support Xcode 9.3?

### ISSUE THREAD

**Issue by ILI4S** [ginowu7/CustomSimulatorsExample#1]
On Xcode 9.3, building the project did not create a `Custom Simulators` iOS simulator device. There appears no Build Pre-action defined for CustomSimulatorsExample. Defining one to run the script as in Build Phases and building the project also does not create a custom iOS simulator target.

**Comment by ginowu7** [comment]
Great catch! I'm making an update on the script soon -

**Comment by ginowu7** [comment]
https://github.com/ginowu7/CustomSimulatorsExample/pull/2

Heres an update - let me know if this fixes the issue for you. Thanks!

**Comment by ginowu7** [comment]
Merged fix - closing this ticket
